"""initial tables

Revision ID: d2e531d14916
Revises: 
Create Date: 2026-10-05 14:36:05.737347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2e531d14916'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False, comment='price/pest_disease'),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True, comment='预测目标'),
    sa.Column('algorithm', sa.String(length=64), nullable=True),
    sa.Column('training_dataset', sa.String(length=255), nullable=True),
    sa.Column('evaluation_metric', sa.String(length=64), nullable=True, comment='评估指标名'),
    sa.Column('accuracy', sa.Numeric(precision=8, scale=4), nullable=True, comment='指标值'),
    sa.Column('model_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/retired'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pest_disease_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='病虫害名称'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='disease病害/pest虫害'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prevention_method', sa.Text(), nullable=True, comment='防治措施'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='区域名称'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='类型: country/province/city/county'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级区域'),
    sa.Column('adcode', sa.String(length=12), nullable=True, comment='行政区划码（地图钻取）'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('boundary', sa.Text(), nullable=True, comment='地图边界信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False, comment='角色名'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='admin/operator/viewer'),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='销售省份'),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sales_volume', sa.Numeric(precision=12, scale=2), nullable=False, comment='销售数量(吨)'),
    sa.Column('sales_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='销售额(万元)'),
    sa.Column('market_share', sa.Numeric(precision=6, scale=2), nullable=True, comment='市场占比(%)'),
    sa.Column('market_level', sa.String(length=16), nullable=False, comment='等级: core核心/main主要/potential潜力'),
    sa.Column('growth_rate', sa.Numeric(precision=8, scale=2), nullable=True, comment='同比增长率(%)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_area',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='产地名称'),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='所属县区'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('planting_area', sa.Numeric(precision=12, scale=2), nullable=True, comment='种植面积(亩)'),
    sa.Column('main_variety', sa.String(length=64), nullable=True, comment='主要品种'),
    sa.Column('production_technology_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='生产技术分'),
    sa.Column('transport_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='运输能力分'),
    sa.Column('supply_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='供应能力分'),
    sa.Column('benefit_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='综合效益分'),
    sa.Column('description', sa.Text(), nullable=True, comment='产地特点'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False, comment='启用/禁用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('operation', sa.String(length=128), nullable=False, comment='操作描述'),
    sa.Column('module', sa.String(length=64), nullable=True, comment='模块'),
    sa.Column('request_method', sa.String(length=8), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True, comment='success/failure'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pest_disease_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_area_id', sa.BigInteger(), nullable=False),
    sa.Column('pest_disease_type_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='发生时间'),
    sa.Column('affected_area', sa.Numeric(precision=12, scale=2), nullable=True, comment='影响面积(亩)'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='影响程度: mild/moderate/severe'),
    sa.Column('production_impact', sa.Numeric(precision=10, scale=2), nullable=True, comment='产量影响(吨)'),
    sa.Column('prevention_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='防治成本(万元)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pest_disease_type_id'], ['pest_disease_type.id'], ),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('production_area_id', sa.BigInteger(), nullable=True),
    sa.Column('prediction_type', sa.String(length=32), nullable=False, comment='price/production/sales/market_demand/pest_disease'),
    sa.Column('prediction_date', sa.Date(), nullable=False, comment='预测生成时间'),
    sa.Column('target_date', sa.Date(), nullable=False, comment='预测目标时间'),
    sa.Column('predicted_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True, comment='low低/medium中/high高（病虫害预测用）'),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='产品名称'),
    sa.Column('variety', sa.String(length=64), nullable=True, comment='品种，如纽荷尔/朋娜'),
    sa.Column('grade', sa.String(length=32), nullable=True, comment='产品等级'),
    sa.Column('specification', sa.String(length=64), nullable=True, comment='产品规格'),
    sa.Column('listing_time', sa.String(length=32), nullable=True, comment='上市时间'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品特点'),
    sa.Column('production_area_id', sa.BigInteger(), nullable=True, comment='所属产地'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_evaluation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_area_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('price_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='价格分'),
    sa.Column('technology_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('transport_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('supply_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('benefit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='综合竞争力评分'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('decision_advice',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('production_area_id', sa.BigInteger(), nullable=True),
    sa.Column('advice_type', sa.String(length=32), nullable=False, comment='price/pest_disease/market/supply'),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['related_prediction_id'], ['prediction_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_area_id', sa.BigInteger(), nullable=False, comment='产地'),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=8, scale=2), nullable=False, comment='平均价(元/kg)'),
    sa.Column('highest_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=8, scale=2), nullable=True, comment='批发价(元/kg)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_area_id', 'product_id', 'date', name='uq_price_area_product_date')
    )
    op.create_table('production_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_area_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False, comment='生产时间'),
    sa.Column('planting_area', sa.Numeric(precision=12, scale=2), nullable=True, comment='种植面积(亩)'),
    sa.Column('production', sa.Numeric(precision=12, scale=2), nullable=False, comment='产量(吨)'),
    sa.Column('yield_per_area', sa.Numeric(precision=10, scale=2), nullable=True, comment='单位面积产量(吨/亩)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_area_id', 'product_id', 'date', name='uq_production_area_product_date')
    )
    op.create_table('sales_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='销售地区'),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False, comment='销售时间'),
    sa.Column('sales_volume', sa.Numeric(precision=12, scale=2), nullable=False, comment='销量(吨)'),
    sa.Column('sales_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='销售额(万元)'),
    sa.Column('sales_channel', sa.String(length=32), nullable=True, comment='渠道: 批发/电商/出口/商超'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'product_id', 'date', 'sales_channel', name='uq_sales_row')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_data')
    op.drop_table('production_data')
    op.drop_table('price_data')
    op.drop_table('decision_advice')
    op.drop_table('refresh_token')
    op.drop_table('production_evaluation')
    op.drop_table('product')
    op.drop_table('prediction_result')
    op.drop_table('pest_disease_record')
    op.drop_table('operation_log')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('production_area')
    op.drop_table('market_data')
    op.drop_table('role')
    op.drop_table('region')
    op.drop_table('pest_disease_type')
    op.drop_table('permission')
    op.drop_table('model_info')
    # ### end Alembic commands ###
